require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - vendor/**/*
Metrics/BlockLength:
  Exclude:
    - nano_rpc.gemspec
    - spec/**/*
RSpec/SubjectStub:
  Exclude:
    - spec/**/*
